### ISSUE TITLE
Panic on range without assignment

### ISSUE THREAD

**Issue by TS-OneShot** [securego/gosec#475]
### Summary 
gosec panics when scanning files containing a `range` statement without an accompanying assignment. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12b3197]

goroutine 1 [running]:
github.com/securego/gosec/v2/rules.(*implicitAliasing).Match(0xc00049e540, 0x13dd580, 0xc0004fca00, 0xc0000cc000, 0x1680380, 0x0, 0xa)
	/Users/TS-OneShot/go/pkg/mod/github.com/securego/gosec/v2@v2.3.0/rules/implicit_aliasing.go:36 +0x287
github.com/securego/gosec/v2.(*Analyzer).Visit(0xc00049e0c0, 0x13dd580, 0xc0004fca00, 0x13db480, 0xc00049e0c0)
	/Users/TS-OneShot/go/pkg/mod/github.com/securego/gosec/v2@v2.3.0/analyzer.go:353 +0x477
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dd580, 0xc0004fca00)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:52 +0x66
go/ast.walkStmtList(0x13db480, 0xc00049e0c0, 0xc0002c3240, 0x3, 0x4)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dcd00, 0xc000c66f60)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dd300, 0xc0002c3600)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:231 +0x1c73
go/ast.walkStmtList(0x13db480, 0xc00049e0c0, 0xc00005d870, 0x1, 0x1)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dce40, 0xc0002c3640)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:260 +0x21e5
go/ast.walkStmtList(0x13db480, 0xc00049e0c0, 0xc00028a6a0, 0x2, 0x2)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dcd00, 0xc000c673b0)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dd600, 0xc00005d990)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:263 +0x1684
go/ast.walkStmtList(0x13db480, 0xc00049e0c0, 0xc00005d9a0, 0x1, 0x1)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dcd00, 0xc000c673e0)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dd140, 0xc0002c38c0)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:275 +0x6e0
go/ast.walkStmtList(0x13db480, 0xc00049e0c0, 0xc000164200, 0xa, 0x10)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dcd00, 0xc000c67410)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:224 +0x1b67
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dd180, 0xc000c67440)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:344 +0xd73
go/ast.walkDeclList(0x13db480, 0xc00049e0c0, 0xc000162400, 0x8, 0x8)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0x13db480, 0xc00049e0c0, 0x13dd100, 0xc000162d00)
	/usr/local/Cellar/go/1.12.1/libexec/src/go/ast/walk.go:353 +0x2659
github.com/securego/gosec/v2.(*Analyzer).Check(0xc00049e0c0, 0xc0002f27e0)
	/Users/TS-OneShot/go/pkg/mod/github.com/securego/gosec/v2@v2.3.0/analyzer.go:219 +0x439
github.com/securego/gosec/v2.(*Analyzer).Process(0xc00049e0c0, 0x0, 0x0, 0x0, 0xc00005c860, 0x1, 0x1, 0x1, 0x0)
	/Users/TS-OneShot/go/pkg/mod/github.com/securego/gosec/v2@v2.3.0/analyzer.go:140 +0xfb
main.main()
	/Users/TS-OneShot/go/pkg/mod/github.com/securego/gosec/v2@v2.3.0/cmd/gosec/main.go:335 +0x79b
```

Can occur with use of `for _, _ = range someMap {` as well as `for key, value = range someMap {`, but does not occur for `for range someMap {`. Issue appears to be caused by assumption that it is guaranteed that there will be an underlying object bound by range; mentioned in `implicit_aliasing.go`: 
```
        // When presented with a range statement, get the underlying Object bound to
        // by assignment and add it to our set (r.aliases) of objects to check for.
```

### Steps to reproduce the behavior
Create `example.go` file:
```
package main

import (
    "fmt"
)

func main() {
    sampleMap := map[string]string{}

    sampleString := "A string"

    for sampleString, _ = range sampleMap {
        fmt.Println(sampleString)
    }   
}
```

Run `gosec ./...`

### gosec version
```$ gosec -version
Version: 
Git tag: 
Build date: 
```

Installed using `go get github.com/securego/gosec/v2/cmd/gosec/` which said `latest`; I believe it is version `2.3.0`. 

### Go version (output of 'go version')
go version go1.12.1 darwin/amd64

### Operating system / Environment
MacOS 10.15.4

### Expected behavior
Continued operation

### Actual behavior
panic

**Comment by gcmurphy** [comment]
Thanks for reporting this. I have reproduced this and will try to get a fix out soon.

**Comment by TS-OneShot** [comment]
Great! Thanks for the quick turnaround!
