### ISSUE TITLE
gosec panics while scannig the project with nil pointer dereference

### ISSUE THREAD

**Issue by C0rWin** [securego/gosec#746]
### Summary
 
While running `gosec` on the project the tool fails with panic. The stack trace is:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1231d3e]

goroutine 1 [running]:
go/token.(*File).Name(...)
        /usr/local/opt/go/libexec/src/go/token/position.go:113
github.com/securego/gosec.(*Analyzer).Check(0xc000164b40, 0xc0017eeb40)
        /Users/c0rwin/golang/pkg/mod/github.com/securego/gosec@v0.0.0-20200401082031-e946c8c39989/analyzer.go:202 +0x11e
github.com/securego/gosec.(*Analyzer).Process(0xc000164b40, {0x0, 0xc0000ae0b8, 0xc0010b4000}, {0xc0010b9000, 0x4ac, 0x3a})
        /Users/c0rwin/golang/pkg/mod/github.com/securego/gosec@v0.0.0-20200401082031-e946c8c39989/analyzer.go:140 +0x169
main.main()
        /Users/c0rwin/golang/pkg/mod/github.com/securego/gosec@v0.0.0-20200401082031-e946c8c39989/cmd/gosec/main.go:329 +0x7c5
```

gosec is compiled from the latest.

**Comment by C0rWin** [comment]
thanks
