### ISSUE TITLE
Invalid sarif file produced by gosec.

### ISSUE THREAD

**Issue by cryanbrow** [securego/gosec#870]
### Summary 

sarif file is invalid because of null object in relationships section of the second rule. Removing the relationship section entirely produces a valid sarif file.

```
Error: Unable to upload "results.sarif" as it is not valid SARIF:
- instance.runs[0].tool.driver.rules[1].relationships[0] is not of a type(s) object
Error: Unable to upload "results.sarif" as it is not valid SARIF:
- instance.runs[0].tool.driver.rules[1].relationships[0] is not of a type(s) object
    at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:203:15)
    at uploadFiles (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:267:9)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:139:18)
    at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:49:30)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:71:9)
```

```
"tool":{
        "driver":{
          "guid":"8b518d5f-906d-39f9-894b-d327b1a421c5",
          "informationUri":"https://github.com/securego/gosec/",
          "name":"gosec",
          "rules":[
            {
              "defaultConfiguration":{
                "level":"warning"
              },
              "fullDescription":{
                "text":"Errors unhandled."
              },
              "help":{
                "text":"Errors unhandled.\nSeverity: LOW\nConfidence: HIGH\n"
              },
              "id":"G104",
              "name":"Improper Check or Handling of Exceptional Conditions",
              "properties":{
                "precision":"high",
                "tags":[
                  "security",
                  "LOW"
                ]
              },
              "relationships":[
                {
                  "kinds":[
                    "superset"
                  ],
                  "target":{
                    "guid":"7df38d1d-038e-3ced-8601-8d9265b90a25",
                    "id":"703",
                    "toolComponent":{
                      "guid":"f2856fc0-85b7-373f-83e7-6f8582243547",
                      "name":"CWE"
                    }
                  }
                }
              ],
              "shortDescription":{
                "text":"Errors unhandled."
              }
            },
            {
              "defaultConfiguration":{
                "level":"error"
              },
              "fullDescription":{
                "text":"Use of net/http serve function that has no support for setting timeouts"
              },
              "help":{
                "text":"Use of net/http serve function that has no support for setting timeouts\nSeverity: MEDIUM\nConfidence: HIGH\n"
              },
              "id":"G114",
              "name":"G114",
              "properties":{
                "precision":"high",
                "tags":[
                  "security",
                  "MEDIUM"
                ]
              },
              "relationships":[
                null
              ],
              "shortDescription":{
                "text":"Use of net/http serve function that has no support for setting timeouts"
              }
            },
```

### Steps to reproduce the behavior
Code for reproducing this is available here: https://github.com/cryanbrow/eve-graphql-go
Running the github workflow produces the error with the actions: 

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        # we let the report trigger content trigger a failure using the GitHub Security features.
        args: '-no-fail -fmt sarif -out results.sarif ./...'

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif

### gosec version

securego/gosec@master

### Go version (output of 'go version')

1.17

### Operating system / Environment

Github Actions

### Expected behavior

Produces a valid sarif file

### Actual behavior

Produces a sarif file with a null relationship under rules.
[results.sarif.txt](https://github.com/securego/gosec/files/9664718/results.sarif.txt)

**Comment by mmorel-35** [comment]
Hi @ccojocar , 
It seems that cwe-676 is missing in https://github.com/securego/gosec/blob/master/cwe/data.go  , which is causing the null in the sarif file

**Comment by davidaparicio** [comment]
I had the same issue with G114 (cf https://github.com/securego/gosec/issues/861).
Is it possible to have a new release of the gosec tool with the latest commit ?

Do we need to create a G114 ID into cwe/data.go like https://github.com/davidaparicio/gosec/blob/master/cwe/data.go#L138-L140 ? If yes, I will create a PR :)

Thanks for your answers !
